const brands = [
  {
    id: "brand_dior",
    name: "Dior",
    country: "France",
    tier: "designer",
    officialWebsite: "https://www.dior.com",
    active: true
  },
  {
    id: "brand_chanel",
    name: "Chanel",
    country: "France",
    tier: "designer",
    officialWebsite: "https://www.chanel.com",
    active: true
  },
  {
    id: "brand_ysl",
    name: "Yves Saint Laurent",
    country: "France",
    tier: "designer",
    officialWebsite: "https://www.yslbeauty.com",
    active: true
  },
  {
    id: "brand_tom_ford",
    name: "Tom Ford",
    country: "United States",
    tier: "luxury-designer",
    officialWebsite: "https://www.tomford.com",
    active: true
  },
  {
    id: "brand_armani",
    name: "Giorgio Armani",
    country: "Italy",
    tier: "designer",
    officialWebsite: "https://www.armani.com",
    active: true
  },
  {
    id: "brand_creed",
    name: "Creed",
    country: "France",
    tier: "niche",
    officialWebsite: "https://www.creedboutique.com",
    active: true
  },
  {
    id: "brand_mfk",
    name: "Maison Francis Kurkdjian",
    country: "France",
    tier: "niche",
    officialWebsite: "https://www.franciskurkdjian.com",
    active: true
  },
  {
    id: "brand_hermes",
    name: "Hermes",
    country: "France",
    tier: "designer",
    officialWebsite: "https://www.hermes.com",
    active: true
  }
];

const perfumes = [
  {
    id: "perfume_sauvage_edp",
    brandId: "brand_dior",
    name: "Sauvage Eau de Parfum",
    family: ["woody", "fresh", "spicy"],
    topNotes: ["bergamot"],
    heartNotes: ["lavender", "spices"],
    baseNotes: ["ambroxan", "vanilla"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["everyday", "date-night", "signature"],
    climates: ["all-year", "cool"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["mass-appeal", "modern", "versatile"],
    sourceConfidence: 0.88
  },
  {
    id: "perfume_dior_homme_sport",
    brandId: "brand_dior",
    name: "Dior Homme Sport",
    family: ["fresh", "citrus", "woody"],
    topNotes: ["lemon", "bergamot"],
    heartNotes: ["elemi", "pink pepper"],
    baseNotes: ["woods", "frankincense"],
    projection: "moderate",
    longevityBand: "balanced",
    useCases: ["everyday", "office", "signature"],
    climates: ["hot", "all-year"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["sporty", "clean", "versatile"],
    sourceConfidence: 0.84
  },
  {
    id: "perfume_bleu_de_chanel_edp",
    brandId: "brand_chanel",
    name: "Bleu de Chanel Eau de Parfum",
    family: ["woody", "fresh", "citrus"],
    topNotes: ["grapefruit", "lemon"],
    heartNotes: ["ginger", "mint"],
    baseNotes: ["cedar", "incense", "sandalwood"],
    projection: "moderate",
    longevityBand: "long",
    useCases: ["office", "everyday", "signature"],
    climates: ["all-year", "hot", "cool"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["refined", "versatile", "professional"],
    sourceConfidence: 0.9
  },
  {
    id: "perfume_chance_eau_tendre",
    brandId: "brand_chanel",
    name: "Chance Eau Tendre",
    family: ["floral", "fresh", "citrus"],
    topNotes: ["grapefruit", "quince"],
    heartNotes: ["jasmine", "rose"],
    baseNotes: ["white musk"],
    projection: "soft",
    longevityBand: "balanced",
    useCases: ["everyday", "office", "gift"],
    climates: ["hot", "all-year"],
    genderDirection: "feminine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["airy", "crowd-pleasing", "elegant"],
    sourceConfidence: 0.87
  },
  {
    id: "perfume_libre_edp",
    brandId: "brand_ysl",
    name: "Libre Eau de Parfum",
    family: ["floral", "amber", "sweet"],
    topNotes: ["mandarin", "lavender"],
    heartNotes: ["orange blossom", "jasmine"],
    baseNotes: ["vanilla", "ambergris"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["date-night", "special-occasion", "signature"],
    climates: ["cool", "all-year"],
    genderDirection: "feminine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["glamorous", "modern", "confident"],
    sourceConfidence: 0.86
  },
  {
    id: "perfume_y_edp",
    brandId: "brand_ysl",
    name: "Y Eau de Parfum",
    family: ["fresh", "woody", "sweet"],
    topNotes: ["apple", "bergamot"],
    heartNotes: ["sage", "juniper"],
    baseNotes: ["amberwood", "tonka bean"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["everyday", "date-night", "signature"],
    climates: ["all-year", "cool"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["trendy", "youthful", "mass-appeal"],
    sourceConfidence: 0.85
  },
  {
    id: "perfume_ombre_leather",
    brandId: "brand_tom_ford",
    name: "Ombre Leather",
    family: ["woody", "amber", "spicy"],
    topNotes: ["cardamom"],
    heartNotes: ["leather", "jasmine sambac"],
    baseNotes: ["amber", "moss", "patchouli"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["date-night", "special-occasion"],
    climates: ["cool"],
    genderDirection: "unisex",
    priceTier: "200-plus",
    brandScope: "major",
    tags: ["bold", "luxury", "statement"],
    sourceConfidence: 0.89
  },
  {
    id: "perfume_neroli_portofino",
    brandId: "brand_tom_ford",
    name: "Neroli Portofino",
    family: ["fresh", "citrus", "floral"],
    topNotes: ["bergamot", "lemon", "mandarin"],
    heartNotes: ["neroli", "orange blossom"],
    baseNotes: ["amber"],
    projection: "moderate",
    longevityBand: "light",
    useCases: ["everyday", "office", "special-occasion"],
    climates: ["hot"],
    genderDirection: "unisex",
    priceTier: "200-plus",
    brandScope: "major",
    tags: ["luxury", "coastal", "bright"],
    sourceConfidence: 0.82
  },
  {
    id: "perfume_acqua_di_gio_profondo",
    brandId: "brand_armani",
    name: "Acqua di Gio Profondo",
    family: ["fresh", "citrus", "woody"],
    topNotes: ["marine notes", "bergamot"],
    heartNotes: ["rosemary", "lavender"],
    baseNotes: ["mineral amber", "patchouli"],
    projection: "moderate",
    longevityBand: "balanced",
    useCases: ["everyday", "office", "signature"],
    climates: ["hot", "all-year"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["clean", "aquatic", "easy-wear"],
    sourceConfidence: 0.84
  },
  {
    id: "perfume_si_edp",
    brandId: "brand_armani",
    name: "Si Eau de Parfum",
    family: ["sweet", "floral", "musky"],
    topNotes: ["blackcurrant"],
    heartNotes: ["rose", "freesia"],
    baseNotes: ["patchouli", "vanilla", "musk"],
    projection: "moderate",
    longevityBand: "long",
    useCases: ["date-night", "signature", "gift"],
    climates: ["cool", "all-year"],
    genderDirection: "feminine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["elegant", "romantic", "mainstream-luxury"],
    sourceConfidence: 0.83
  },
  {
    id: "perfume_aventus",
    brandId: "brand_creed",
    name: "Aventus",
    family: ["fresh", "woody", "citrus"],
    topNotes: ["pineapple", "bergamot"],
    heartNotes: ["birch", "jasmine"],
    baseNotes: ["oakmoss", "musk"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["signature", "special-occasion", "office"],
    climates: ["all-year"],
    genderDirection: "masculine",
    priceTier: "200-plus",
    brandScope: "open",
    tags: ["status", "refined", "iconic"],
    sourceConfidence: 0.88
  },
  {
    id: "perfume_silver_mountain_water",
    brandId: "brand_creed",
    name: "Silver Mountain Water",
    family: ["fresh", "citrus", "musky"],
    topNotes: ["bergamot", "mandarin"],
    heartNotes: ["green tea", "blackcurrant"],
    baseNotes: ["musk", "petitgrain"],
    projection: "moderate",
    longevityBand: "balanced",
    useCases: ["office", "everyday", "signature"],
    climates: ["hot", "all-year"],
    genderDirection: "unisex",
    priceTier: "200-plus",
    brandScope: "open",
    tags: ["airy", "clean", "mountain-fresh"],
    sourceConfidence: 0.81
  },
  {
    id: "perfume_baccarat_rouge_540",
    brandId: "brand_mfk",
    name: "Baccarat Rouge 540",
    family: ["amber", "sweet", "woody"],
    topNotes: ["saffron", "jasmine"],
    heartNotes: ["amberwood", "ambergris"],
    baseNotes: ["fir resin", "cedar"],
    projection: "strong",
    longevityBand: "long",
    useCases: ["special-occasion", "date-night", "signature"],
    climates: ["cool", "all-year"],
    genderDirection: "unisex",
    priceTier: "200-plus",
    brandScope: "open",
    tags: ["luxury", "statement", "viral"],
    sourceConfidence: 0.9
  },
  {
    id: "perfume_aqua_universalis",
    brandId: "brand_mfk",
    name: "Aqua Universalis",
    family: ["fresh", "citrus", "musky"],
    topNotes: ["bergamot", "lemon"],
    heartNotes: ["white flowers"],
    baseNotes: ["musk", "light woods"],
    projection: "soft",
    longevityBand: "balanced",
    useCases: ["office", "everyday", "gift"],
    climates: ["hot", "all-year"],
    genderDirection: "unisex",
    priceTier: "200-plus",
    brandScope: "open",
    tags: ["clean", "linen-fresh", "elegant"],
    sourceConfidence: 0.8
  },
  {
    id: "perfume_terre_dhermes",
    brandId: "brand_hermes",
    name: "Terre d'Hermes",
    family: ["woody", "citrus", "spicy"],
    topNotes: ["orange", "grapefruit"],
    heartNotes: ["pepper", "geranium"],
    baseNotes: ["vetiver", "cedar", "benzoin"],
    projection: "moderate",
    longevityBand: "long",
    useCases: ["office", "signature", "special-occasion"],
    climates: ["all-year", "cool"],
    genderDirection: "masculine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["refined", "earthy", "classic"],
    sourceConfidence: 0.89
  },
  {
    id: "perfume_twilly",
    brandId: "brand_hermes",
    name: "Twilly d'Hermes",
    family: ["floral", "spicy", "sweet"],
    topNotes: ["ginger"],
    heartNotes: ["tuberose"],
    baseNotes: ["sandalwood"],
    projection: "moderate",
    longevityBand: "balanced",
    useCases: ["everyday", "date-night", "gift"],
    climates: ["all-year", "cool"],
    genderDirection: "feminine",
    priceTier: "100-200",
    brandScope: "major",
    tags: ["playful", "chic", "modern"],
    sourceConfidence: 0.83
  }
];

function getBrandById(brandId) {
  return brands.find((brand) => brand.id === brandId) || null;
}

module.exports = {
  brands,
  perfumes,
  getBrandById
};
